name: continuous integration
on:
  push:
    branches:
      - main
jobs:
  server_job:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # execute commands
          script: sh ~/scripts/continuous-integration/api.sh
